### ISSUE TITLE
current version issues

### ISSUE THREAD

**Issue by jezdd** [HelTecAutomation/platform-heltec-cubecell#1]
Unsure what is going on with versions here, the latest update is applied to the develop branch? why is this?

I am using platform = https://github.com/HelTecAutomation/platform-asrmicro650x.git#develop but its still not picking up as 1.6 release, and of course its the old 1.4 framework release.

Can we get a full release with the latest framework package 1.5 too, we are lagging behind.

Cheers

Jez

**Comment by ivankravets** [comment]
Please with to the new dev-platform https://registry.platformio.org/platforms/heltecautomation/heltec-cubecell
